### ISSUE TITLE
No module named 'langchain.globals'

### ISSUE THREAD

**Issue by ujaved** [shuuse/ChatTDD#1]
After setting the openai api key , when I run `chattdd`, I get the error:

```
ujaved@Umars-MacBook-Pro ~ % chattdd
Traceback (most recent call last):
  File "/usr/local/bin/chattdd", line 5, in <module>
    from chattdd.cli import cli
  File "/usr/local/lib/python3.11/site-packages/chattdd/cli.py", line 2, in <module>
    from chattdd.logic import set_output_folder, generate_and_save_logic, set_model
  File "/usr/local/lib/python3.11/site-packages/chattdd/logic.py", line 2, in <module>
    from chattdd.core import initialize_model, generate_test_code, review_test_code
  File "/usr/local/lib/python3.11/site-packages/chattdd/core.py", line 7, in <module>
    from langchain.globals import set_llm_cache
ModuleNotFoundError: No module named 'langchain.globals'
```

**Comment by shuuse** [comment]
Hi @ujaved ! Please dump the output of " python -m pip show langchain " here.

**Comment by ujaved** [comment]
```
python3 -m pip show langchain
Name: langchain
Version: 0.0.330
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author:
Author-email:
License: MIT
Location: /usr/local/lib/python3.11/site-packages
Requires: aiohttp, anyio, dataclasses-json, jsonpatch, langsmith, numpy, pydantic, PyYAML, requests, SQLAlchemy, tenacity
Required-by: ChatTDD, llama-index
```

**Comment by shuuse** [comment]
Thanks. I haven't seen that issue before and cannot replicate. Maybe see if you can get the langchain examples running? https://python.langchain.com/docs/modules/model_io/models/llms/llm_caching
